// <auto-generated />
using FinalProject_IT212.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject_IT212.Migrations
{
    [DbContext(typeof(FinalProject_IT212Context))]
    [Migration("20241207070844_AddedSeedData")]
    partial class AddedSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject_IT212.Models.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "BalloonGirl657@Treemail.com",
                            FirstName = "Lisa",
                            LastName = "Hedgington"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "CrysanthimumPedals@Treemail.com",
                            FirstName = "Margaret",
                            LastName = "Tanding"
                        },
                        new
                        {
                            CustomerId = 3,
                            Email = "CamileIanHearts@Treemail.com",
                            FirstName = "Camile",
                            LastName = "Smith"
                        },
                        new
                        {
                            CustomerId = 4,
                            Email = "RocksNFries@Treemail.com",
                            FirstName = "Michael",
                            LastName = "Odderton"
                        },
                        new
                        {
                            CustomerId = 5,
                            Email = "PearlsAndBlooms347@YahootieHoo.com",
                            FirstName = "Helen",
                            LastName = "McBride"
                        });
                });

            modelBuilder.Entity("FinalProject_IT212.Models.Orders", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("OrderCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderCost = 53.78m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 4,
                            OrderCost = 89.64m
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 3,
                            OrderCost = 32.78m
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 2,
                            OrderCost = 338.31m
                        },
                        new
                        {
                            OrderId = 5,
                            CustomerId = 1,
                            OrderCost = 127.44m
                        });
                });

            modelBuilder.Entity("FinalProject_IT212.Models.Products", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Cost = 53.78m,
                            Description = "Cream floral",
                            Name = "Blouse"
                        },
                        new
                        {
                            ProductId = 2,
                            Cost = 73.66m,
                            Description = "Brown cordoroy",
                            Name = "Bell Bottoms"
                        },
                        new
                        {
                            ProductId = 3,
                            Cost = 65.99m,
                            Description = "Green moose decal",
                            Name = "Hoodie"
                        },
                        new
                        {
                            ProductId = 4,
                            Cost = 7.99m,
                            Description = "Black",
                            Name = "Basic T-shirt"
                        },
                        new
                        {
                            ProductId = 5,
                            Cost = 32.78m,
                            Description = "Maroon lace",
                            Name = "Crop Top"
                        });
                });

            modelBuilder.Entity("FinalProject_IT212.Models.Quantity", b =>
                {
                    b.Property<int>("QuantityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuantityId"));

                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductQty")
                        .HasColumnType("int");

                    b.HasKey("QuantityId");

                    b.HasIndex("OrdersOrderId");

                    b.ToTable("Quantity");

                    b.HasData(
                        new
                        {
                            QuantityId = 1,
                            OrdersOrderId = 1,
                            ProductId = 1,
                            ProductQty = 1
                        },
                        new
                        {
                            QuantityId = 2,
                            OrdersOrderId = 2,
                            ProductId = 2,
                            ProductQty = 1
                        },
                        new
                        {
                            QuantityId = 3,
                            OrdersOrderId = 2,
                            ProductId = 4,
                            ProductQty = 2
                        },
                        new
                        {
                            QuantityId = 4,
                            OrdersOrderId = 3,
                            ProductId = 5,
                            ProductQty = 1
                        },
                        new
                        {
                            QuantityId = 5,
                            OrdersOrderId = 4,
                            ProductId = 1,
                            ProductQty = 2
                        },
                        new
                        {
                            QuantityId = 6,
                            OrdersOrderId = 4,
                            ProductId = 5,
                            ProductQty = 1
                        },
                        new
                        {
                            QuantityId = 7,
                            OrdersOrderId = 4,
                            ProductId = 3,
                            ProductQty = 3
                        },
                        new
                        {
                            QuantityId = 8,
                            OrdersOrderId = 5,
                            ProductId = 1,
                            ProductQty = 1
                        },
                        new
                        {
                            QuantityId = 9,
                            OrdersOrderId = 5,
                            ProductId = 2,
                            ProductQty = 1
                        });
                });

            modelBuilder.Entity("FinalProject_IT212.Models.Quantity", b =>
                {
                    b.HasOne("FinalProject_IT212.Models.Orders", null)
                        .WithMany("ProductQty")
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProject_IT212.Models.Orders", b =>
                {
                    b.Navigation("ProductQty");
                });
#pragma warning restore 612, 618
        }
    }
}
